export default CarouselInfo = [
  {
    id: '10576',
    name: 'Pizza Hut',
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2024/7/16/87e56c63-b521-4257-96ae-a42229b92009_10576.jpg',
    locality: '6th Block',
    areaName: 'Koramangala',
    costForTwo: '₹350 for two',
    cuisines: ['Pizzas'],
    avgRating: 4.3,
    parentId: '721',
    avgRatingString: '4.3',
    totalRatingsString: '21K+',
    sla: {
      deliveryTime: 31,
      lastMileTravel: 0.9,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '0.9 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    availability: {
      nextCloseTime: '2025-02-11 04:00:00',
      opened: true,
    },
    badges: {},
  },
  {
    id: '656392',
    name: 'Subway',
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2025/1/21/ccb97e93-5b1a-4e18-9dd7-3f635e2d5e94_656392.JPG',
    locality: '1st Block',
    areaName: 'Koramangala',
    costForTwo: '₹350 for two',
    cuisines: ['sandwich', 'Salads', 'wrap', 'Healthy Food'],
    avgRating: 4.3,
    parentId: '2',
    avgRatingString: '4.3',
    totalRatingsString: '3.4K+',
    sla: {
      deliveryTime: 19,
      lastMileTravel: 1.6,
      serviceability: 'SERVICEABLE',
      slaString: '15-20 mins',
      lastMileTravelString: '1.6 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
  },
  {
    id: '561280',
    name: 'Baskin Robbins Happyness Shakes',
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2024/9/12/ab783fda-caaf-4fc5-be60-08b08f322700_561280.JPG',
    locality: 'Koramangala',
    areaName: 'Koramangala',
    costForTwo: '₹250 for two',
    cuisines: ['Beverages', 'Desserts'],
    parentId: '5588',
    avgRatingString: '--',
    sla: {
      deliveryTime: 28,
      lastMileTravel: 0.6,
      serviceability: 'SERVICEABLE',
      slaString: '25-30 mins',
      lastMileTravelString: '0.6 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
  },
  {
    id: '747259',
    name: 'FreshMenu',
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2025/2/7/e039a880-fd39-4639-a035-256911e91928_747259.jpg',
    locality: 'EJIPURA',
    areaName: 'Koramangala',
    costForTwo: '₹250 for two',
    cuisines: [
      'Continental',
      'Chinese',
      'Oriental',
      'Asian',
      'Healthy Food',
      'Fast Food',
      'Indian',
      'Desserts',
    ],
    avgRating: 4.2,
    parentId: '398',
    avgRatingString: '4.2',
    totalRatingsString: '4.6K+',
    sla: {
      deliveryTime: 30,
      lastMileTravel: 0.7,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '0.7 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
  },
  {
    id: '288678',
    name: 'Home Plate by EatFit',
    cloudinaryImageId: '1d578bb732e03c6f591790eb7d2d88e2',
    locality: '6th Block',
    areaName: 'Koramangala',
    costForTwo: '₹250 for two',
    cuisines: [
      'North Indian',
      'Home Food',
      'Healthy Food',
      'Indian',
      'Punjabi',
      'South Indian',
      'Rajasthani',
      'Maharashtrian',
      'Snacks',
      'Desserts',
    ],
    avgRating: 4.4,
    parentId: '301197',
    avgRatingString: '4.4',
    totalRatingsString: '1.8K+',
    sla: {
      deliveryTime: 21,
      lastMileTravel: 0.9,
      serviceability: 'SERVICEABLE',
      slaString: '20-25 mins',
      lastMileTravelString: '0.9 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
  },
  {
    id: '65797',
    name: "Leon's - Burgers & Wings",
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2024/11/14/33bfb682-d5fa-4054-9e2c-31911e34ebf6_65797.jpg',
    locality: 'Koramangala',
    areaName: 'Koramangala',
    costForTwo: '₹300 for two',
    cuisines: ['American', 'Snacks', 'Turkish', 'Portuguese', 'Continental'],
    avgRating: 4.5,
    parentId: '371281',
    avgRatingString: '4.5',
    totalRatingsString: '55K+',
    sla: {
      deliveryTime: 31,
      lastMileTravel: 1.4,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '1.4 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
  },
  {
    id: '390057',
    name: 'NH1 Bowls - Highway To North',
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/b1e9f652-dc8d-4789-9710-6485ec06846e_390057.jpg',
    locality: '6th Block',
    areaName: 'Koramangala',
    costForTwo: '₹250 for two',
    cuisines: ['North Indian', 'Punjabi', 'Home Food'],
    avgRating: 4.7,
    parentId: '22452',
    avgRatingString: '4.7',
    totalRatingsString: '1.0K+',
    sla: {
      deliveryTime: 15,
      lastMileTravel: 0.8,
      serviceability: 'SERVICEABLE',
      slaString: '10-20 mins',
      lastMileTravelString: '0.8 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
  },
  {
    id: '375041',
    name: 'Andhra Gunpowder',
    cloudinaryImageId: 'byilgyrcfz690ryoasww',
    locality: '6th Block',
    areaName: 'Koramangala',
    costForTwo: '₹350 for two',
    cuisines: ['Andhra', 'Biryani', 'South Indian'],
    avgRating: 4.5,
    parentId: '10496',
    avgRatingString: '4.5',
    totalRatingsString: '5.6K+',
    sla: {
      deliveryTime: 20,
      lastMileTravel: 0.1,
      serviceability: 'SERVICEABLE',
      slaString: '15-20 mins',
      lastMileTravelString: '0.1 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
  },
  // {
  //   id: '750225',
  //   name: 'Daily Kitchen - Homely Meals',
  //   cloudinaryImageId:
  //     'RX_THUMBNAIL/IMAGES/VENDOR/2024/5/19/4ec6a5b6-7c8d-4e10-b8a3-317922e419da_750225.JPG',
  //   locality: '6TH BLOCK',
  //   areaName: 'Koramangala',
  //   costForTwo: '₹250 for two',
  //   cuisines: ['Home Food', 'Indian', 'North Indian', 'Thalis'],
  //   avgRating: 4.4,
  //   parentId: '444382',
  //   avgRatingString: '4.4',
  //   totalRatingsString: '572',
  //   sla: {
  //     deliveryTime: 15,
  //     lastMileTravel: 0.8,
  //     serviceability: 'SERVICEABLE',
  //     slaString: '10-20 mins',
  //     lastMileTravelString: '0.8 km',
  //     iconType: 'ICON_TYPE_EMPTY',
  //   },
  // },
]
